spring:
 profiles:
  active:
   -dev
---
spring:
 profiles: dev   #开发环境
 application:
  name: microservicecloud-config-config-atguigu-dev
---
spring:
 profiles: test #测试环境
 application:
  name: microservicecloud-config-atguigu-test

#请保存为UTF-8格式
---

spring:
 profiles:
  active:
   - dev
---
server:
 prot: 8201
spring:
 profiles: dev
 application:
  name: microservicecloud-config-client
eureka:
 client:
  service-url:
   defaultZone: http;//eureka-dev.com:7001/eureka/

---
server:
 prot: 8202
spring:
 profiles: test
 application:
  name: microservicecloud-config-client
eureka:
 client:
  service-url:
   defaultZone: http;//eureka-test.com:7001/eureka/
---

spring:
 cloud:
  config:
   name: microservicecloud-config-client   #需要从github上读取的资源名称，注意没有yml后缀名
   profile: dev #本次访问的配置项
   label: master
   uri: http://config-3344.com:3344  #本微服务启动后先去找3344号服务，通过SpringCloudConfig获取GitHub的服务地址